#!/usr/bin/env bash

## From here:
## https://wiki.archlinux.org/title/EFI_system_partition#Using_a_mkinitcpio_post_hook

kernel="$1"
initramfs="$2"
target_dir="/efi/EFI/arch"
files_to_copy=()

for file in "$kernel" "$initramfs"; do
	if [[ -n "$file" ]] && ! cmp -s -- "$file" "${target_dir}/${file##*/}"; then
		files_to_copy+=("$file")
	fi
done

(( ! ${#files_to_copy[@]} )) && exit 0

cp -af -- "${files_to_copy[@]}" "${target_dir}/"